# Generated by Django 5.2.7 on 2025-11-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='carbs_g',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='energy_kcal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='fat_g',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='main_ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='protein_g',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
