# Generated by Django 5.2.7 on 2025-11-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RandomFood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='favorite_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
