# Generated by Django 5.2.7 on 2025-11-16 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RandomFood", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Food Category",
                "verbose_name_plural": "Food Categories",
            },
        ),
        migrations.AddField(
            model_name="food",
            name="carb_in_food",
            field=models.FloatField(
                blank=True, help_text="Carbohydrates (g)", null=True
            ),
        ),
        migrations.AddField(
            model_name="food",
            name="fat_in_food",
            field=models.FloatField(blank=True, help_text="Fat (g)", null=True),
        ),
        migrations.AddField(
            model_name="food",
            name="ingredients",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated or newline list of ingredients",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="food",
            name="protein_in_food",
            field=models.FloatField(blank=True, help_text="Protein (g)", null=True),
        ),
        migrations.AddField(
            model_name="food",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="foods",
                to="RandomFood.foodcategory",
            ),
        ),
    ]
