# Generated by Django 5.2.7 on 2025-11-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RandomFood", "0002_foodcategory_food_carb_in_food_food_fat_in_food_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Food Type",
                "verbose_name_plural": "Food Types",
            },
        ),
        migrations.AddField(
            model_name="food",
            name="food_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select one or more types for this food (e.g., Thai, Noodle)",
                related_name="foods",
                to="RandomFood.foodtype",
            ),
        ),
    ]
