# Generated by Django 5.2.7 on 2025-11-16 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RandomFood', '0002_food_favorite_count'),
        ('RandomFood', '0003_foodtype_food_food_types'),
    ]

    operations = [
    ]
